version: '3.9'

services:
  devenv:
    env_file:
      - .env
    container_name: ${USER_NAME}-r-dev
    image: ${USER_NAME}-r${R_VER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=${TAG}
        - R_VER=${R_VER}
    volumes:
      - "/mnt/cho_lab/disk2:/data0"
      - "projects:/projects"
      - "extensions:/root/.vscode-server/extensions"
    tty: true
    restart: always

volumes:
  projects:
    name: ${USER_NAME}
  extensions:
    name: ${USER_NAME}-vsc-extensions

