version: '3.9'

services:
  devenv:
    env_file:
      - .env
    container_name: ${USER_NAME}-r-dev
    image: ${USER_NAME}-r${R_VER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=${TAG}
        - R_VER=${R_VER}
    volumes:
      - "/mnt/data0/cholab/${USER_NAME}:/data0"
      - "projects:/projects"
    tty: true
    restart: always

volumes:
  projects:
    external: true
    name: ${USER_NAME}
